
#define USB_VENDOR_ID	OPENPCD_VENDOR_ID

#ifdef SIMTRACE
#define OPENPCD_PIO_LED2	AT91C_PIO_PA17
#define OPENPCD_PIO_LED1	AT91C_PIO_PA18
#define OPENPCD_PIO_UDP_CNX	AT91C_PIO_PA24
#define OPENPCD_PIO_UDP_PUP	AT91C_PIO_PA16
#define USB_PRODUCT_ID		SIMTRACE_PRODUCT_ID
#else
#error "unknown PCB"
#endif

#define SIMTRACE_PIO_CLK	AT91C_PA2_SCK0
#define SIMTRACE_PIO_IO		AT91C_PA6_TXD0
#define SIMTRACE_PIO_nRST	AT91C_PIO_PA7
